/**
 * Source-of-truth Chinese strings for the pros / cons generated by
 * `generateExplanations`. The keys here MUST match the ones in the
 * app's `apps/web/messages/zh-CN.json` under `opt.pro.*` / `opt.con.*`.
 *
 * Why an inline constant instead of an import: the optimiser package
 * is consumed outside the web app too (and tests rely on the Chinese
 * output via identity-`t()` calls). The constant keeps the engine
 * self-contained while making the keys trivially cross-checkable
 * against the app dictionary.
 */
const DEFAULT_ZH = {
  "opt.pro.costLow": "预期利息成本极低，利息支出控制最佳。",
  "opt.con.costHigh": "预期整体利息成本支出较高。",
  "opt.pro.div.costPremium": "分散化预设下：总成本略高于最优方案，但换来更低的再融资集中度和更高的灵活度。",
  "opt.pro.stabilitySmooth": "还款波动小，还款额平稳，供款保障度高。",
  "opt.con.peakRisk": "高利率情景下面临较高的月供/周供/双周供峰值风险。",
  "opt.pro.paymentPayoffClean": "贷款在合理期限内偿清，无长期挂账风险。",
  "opt.con.paymentPayoffUnfinished": "贷款在模拟期内未能完全偿清，存在挂账风险。",
  "opt.pro.term.principalFast": "本金还款额度大，有利于快速消减贷款余额。",
  "opt.con.term.principalSlow": "本金还款进度较慢，到期剩余余额较多。",
  "opt.con.term.breachHigh": "模拟期内更容易超过设定供款预算。",
  "opt.con.term.budgetHigh": "模拟期内更容易超过设定供款预算。",
  "opt.pro.refix.spread": "贷款到期日期分散，避免集中重定价利率飙升的风险。",
  "opt.con.refix.concurrent": "多笔贷款面临同时到期，重定价利率集中暴露风险高。",
  "opt.pro.div.refixSpread": "分散化预设下：再融资风险分散到不同月份，单次冲击的影响更可控。",
  "opt.con.div.multiTranche": "分散化预设下：管理多个固定到期日稍复杂，需要关注每个子贷款的再融资时点。",
  "opt.pro.div.flexPreserve": "分散化预设下：保留充足的浮动或Offset额度，便于在机会出现时灵活还款或对冲。",
  "opt.pro.flex.high": "保留较高浮动或Offset额度，资金注入与提前还款极具灵活性。",
  "opt.con.flex.locked": "高比例固定锁死了贷款，限制了随时对冲或大额提前还款。",
  "opt.pro.endingBalanceLow": "极端情景下剩余本金较少，债务压缩速度稳定。",
  "opt.con.endingBalanceHigh": "极端情景下剩余本金较多，本金压缩存在不确定性。",
  "opt.pro.volatilityLow": "供款波动小，家庭现金流可预期性高。",
  "opt.con.volatilityHigh": "供款波动较大，临近 refix 时跳升明显，需预备缓冲。",
  "opt.pro.budgetLow": "模拟期内预算超限次数较少，供款压力更可控。",
  "opt.pro.paretoYes": "是（帕累托最优）",
  "opt.pro.paretoNo": "否（被支配）",
  "opt.pro.balanced": "各项财务与风险指标表现较为均衡。",
  "opt.con.noTailDefense": "在极端高息走势下缺乏更深度的防御缓冲。"
};

/**
 * Default translator: returns the Chinese literal for the key, or the
 * key itself (as a self-identifying fallback) when missing. This keeps
 * the engine's behaviour unchanged for legacy callers — the existing
 * Chinese-substring assertions in `optimiser.test.js` continue to pass.
 *
 * @type {(key: string) => string}
 */
const identityT = (/** @type {string} */ key) => DEFAULT_ZH[key] !== undefined ? DEFAULT_ZH[key] : key;

/**
 * Default tolerances for the dominance check, per spec section 9.1 (term mode)
 * and 9.2 (payment mode). The two modes share some keys; payment mode
 * uses `worstCaseEndingBalance` and `payoffTime` instead of
 * `worstCaseInterest` and `expectedAffordabilityBreaches`.
 * @type {Record<string, number>}
 */
export const DEFAULT_TOLERANCES_TERM = {
  // Tightened from $50 -> $20: on a $500k loan over 5 years, $50 is ~0.001% of
  // principal — looser than the typical $500-$5,000 cost gap between strategies.
  // The tighter tolerance widens the Pareto set so 3+ split strategies that
  // tie the 90/10 reference on cost (within $20) but beat it on
  // `expectedMaxConcurrentRefixPercentage` are no longer hidden.
  expectedInterest: 20,
  worstCaseInterest: 50,
  worstCasePayment: 10,
  // 0.01 -> 0.02: refix concentration differences of <2% between two strategies
  // are within noise of the spread product catalogue. Loosening by 2x keeps the
  // Pareto set meaningful without collapsing all strategies into a tie.
  expectedMaxConcurrentRefixPercentage: 0.02,
  // 0.5 -> 1: the user perceives "0 vs 1 budget breach" as equivalent (an off-by-one
  // on the boundary month), but 1 vs 2 as materially worse.
  expectedAffordabilityBreaches: 1,
  // 0.01 -> 0.02: aligns with the refix concentration tolerance since both
  // axes are read off the strategy.allocations share (same denominator).
  flexibilityPenalty: 0.02,
  // NZD/period stddev of monthly scheduled payments. Typical values 5-30 NZD.
  // 0.05 ≈ 0.2-1% of typical payment size — discriminates without collapsing.
  expectedPaymentVolatility: 0.05,
  // NZD; ending balance on a $500k loan is in tens of thousands. 200 NZD
  // tolerance ≈ 0.04% of principal — meaningful but doesn't drown real splits.
  expectedEndingBalance: 200,
  // 1: same boundary semantics as `expectedAffordabilityBreaches`.
  worstCaseAffordabilityBreaches: 1,
  // v9: count type, same boundary semantics as `expectedAffordabilityBreaches`
  // — an off-by-one on the refix event count is within noise of the term
  // length and product catalogue.
  expectedRefixEventCount: 1,
  // v10: max single allocation share; 5pp tolerance matches the 5%/10%
  // step granularity of the NZ product catalogue. Two strategies within 5pp
  // on their largest single tranche are tied for Pareto purposes.
  concentration: 0.05
};

/** @type {Record<string, number>} */
export const DEFAULT_TOLERANCES_PAYMENT = {
  // Same tightening as term mode — see DEFAULT_TOLERANCES_TERM comment.
  expectedInterest: 20,
  worstCaseEndingBalance: 50,
  // 1 -> 3: a 30-year loan's `payoffTime` is fuzzy at the single-month level.
  // ±3 months reflects "拖尾 vs 提前偿清"的实际可感知差异.
  payoffTime: 3,
  expectedMaxConcurrentRefixPercentage: 0.02,
  flexibilityPenalty: 0.02,
  expectedPaymentVolatility: 0.05,
  // v9: count type, same semantics as the term-mode `expectedRefixEventCount`.
  expectedRefixEventCount: 1,
  // v10: max single allocation share; 5pp tolerance matches the 5%/10%
  // step granularity of the NZ product catalogue. See term-mode map.
  concentration: 0.05
};

/**
 * Tolerance-aware dominance check per spec section 9.3.
 * A strategy A dominates B iff:
 *  - For every selected objective, A.objective <= B.objective + tolerance, AND
 *  - For at least one objective, A.objective < B.objective - tolerance.
 *
 * All objectives are minimise.
 *
 * @param {any} a
 * @param {any} b
 * @param {string[]} objectives - Objective keys, all in the minimise direction.
 * @param {Record<string, number>} tolerances
 * @returns {boolean} True if A dominates B within the given tolerances.
 */
export function dominates(a, b, objectives, tolerances) {
  let allWithin = true;
  let anyStrict = false;
  for (const o of objectives) {
    const tol = tolerances[o] !== undefined ? tolerances[o] : 0;
    const diff = a[o] - b[o];
    if (diff > tol) {
      allWithin = false;
    }
    if (diff < -tol) {
      anyStrict = true;
    }
  }
  return allWithin && anyStrict;
}

/**
 * Returns the bound object {min, max, diff} for a metric, with diff fallback to 1
 * for divide-by-zero protection (matches the existing semantics at optimiser.js:157-162).
 * @param {any[]} strategies
 * @param {string} key
 * @returns {{min: number, max: number, diff: number}}
 */
function getBoundsFor(strategies, key) {
  const values = strategies.map((/** @type {any} */ s) => s[key]);
  const min = Math.min(...values);
  const max = Math.max(...values);
  return { min, max, diff: (max - min) || 1 };
}

/**
 * Returns the term-mode Pareto objective set per spec 9.1:
 *   1. expectedInterest ($20)
 *   2. worstCaseInterest ($50)
 *   3. worstCasePayment ($10)
 *   4. expectedMaxConcurrentRefixPercentage (0.02)
 *   5. expectedAffordabilityBreaches (1)
 *   6. flexibilityPenalty = 1 - expectedFloatingExposure (0.02)
 *   7. expectedPaymentVolatility (0.05) — schedule-flow stability
 *   8. expectedEndingBalance (200) — principal paydown speed (term-mode only)
 *   9. worstCaseAffordabilityBreaches (1) — tail budget-breach count
 *   10. expectedRefixEventCount (1) — total refix event count (v9)
 *   11. concentration (0.05) — max single allocation share (v10). The
 *       strategy's largest tranche %. A 50/50 split ties a 55/45 split;
 *       a 100/0 (single-product) is dominated by any 90/10 etc. within
 *       tolerance. Derives from `strategies[].allocations[].percentage`
 *       passed into `optimizeStrategies`; defaults to 1.0 when absent.
 * @param {Record<string, number>} [tolerances]
 * @returns {{objectives: string[], tolerances: Record<string, number>}}
 */
export function getTermObjectives(tolerances = {}) {
  return {
    objectives: [
      "expectedInterest",
      "worstCaseInterest",
      "worstCasePayment",
      "expectedMaxConcurrentRefixPercentage",
      "expectedAffordabilityBreaches",
      "flexibilityPenalty",
      "expectedPaymentVolatility",
      "expectedEndingBalance",
      "worstCaseAffordabilityBreaches",
      "expectedRefixEventCount",
      "concentration"
    ],
    tolerances: { ...DEFAULT_TOLERANCES_TERM, ...tolerances }
  };
}

/**
 * Returns the payment-mode Pareto objective set per spec 9.2:
 *   1. expectedInterest ($20)
 *   2. worstCaseEndingBalance ($50)
 *   3. payoffTime (3)
 *   4. expectedMaxConcurrentRefixPercentage (0.02)
 *   5. flexibilityPenalty (0.02)
 *   6. expectedPaymentVolatility (0.05) — schedule-flow stability
 *   7. worstCaseInterest ($50) — v9 worst-case defense
 *   8. worstCaseAffordabilityBreaches (1) — v9 worst-case defense
 *   9. expectedRefixEventCount (1) — v9 worst-case defense
 *   10. concentration (0.05) — v10, same derivation as term-mode.
 *
 * Note: `expectedEndingBalance` is intentionally NOT a payment-mode objective
 * since `payoffTime` already captures the same signal (loan paid off -> balance
 * = 0; not paid off -> payoffTime > forecastMonths).
 * @param {Record<string, number>} [tolerances]
 * @returns {{objectives: string[], tolerances: Record<string, number>}}
 */
export function getPaymentObjectives(tolerances = {}) {
  return {
    objectives: [
      "expectedInterest",
      "worstCaseEndingBalance",
      "payoffTime",
      "expectedMaxConcurrentRefixPercentage",
      "flexibilityPenalty",
      "expectedPaymentVolatility",
      "worstCaseInterest",
      "worstCaseAffordabilityBreaches",
      "expectedRefixEventCount",
      "concentration"
    ],
    tolerances: { ...DEFAULT_TOLERANCES_PAYMENT, ...tolerances }
  };
}

/**
 * Generates Chinese-language pros/cons for a strategy, given the rank-wide
 * bounds and the operation mode. Exported so the page can use it as the
 * single source of truth (spec 10.4).
 *
 * @param {any} s - Aggregated strategy record (must include the metrics below)
 * @param {Record<string, {min: number, max: number, diff: number}>} bounds
 *   - Map of metric name → {min, max, diff}. Keys include: cost, stability,
 *     endingBalance, refix, flexibility, flex, budget, principal, payoff.
 * @param {"term"|"payment"} mode
 * @param {Object} [opts]
 * @param {boolean} [opts.diversification=false] - When true, the user has
 *   opted into a richer candidate set via the Diversification preset. The
 *   pros/cons emit diversification-flavoured copy: refix-spread and flexible
 *   overpayment are emphasised as pros; multi-tranche management overhead
 *   and slightly higher expected cost are flagged as cons.
 * @returns {{pros: string[], cons: string[]}}
 */
export function generateExplanations(s, bounds, mode = "term", opts = {}) {
  const { diversification = false, t = identityT } = opts;
  /** @type {string[]} */
  const pros = [];
  /** @type {string[]} */
  const cons = [];

  // Interest cost
  if (bounds.cost && s.expectedInterest <= bounds.cost.min + bounds.cost.diff * 0.15) {
    pros.push(t("opt.pro.costLow"));
  } else if (bounds.cost && s.expectedInterest >= bounds.cost.max - bounds.cost.diff * 0.20) {
    cons.push(t("opt.con.costHigh"));
  }

  // Diversification preset: a small expected-interest premium is acceptable
  // because the user explicitly opted into richer candidate sets. Frame it as
  // a known trade-off rather than a pure negative.
  if (diversification && bounds.cost && s.expectedInterest > bounds.cost.min + bounds.cost.diff * 0.15) {
    cons.push(t("opt.con.div.costPremium"));
  }

  // Worst-case payment (term mode) or worst-case ending balance (payment mode)
  if (mode === "term") {
    if (bounds.stability && s.worstCasePayment <= bounds.stability.min + bounds.stability.diff * 0.15) {
      pros.push(t("opt.pro.stabilitySmooth"));
    } else if (bounds.stability && s.worstCasePayment >= bounds.stability.max - bounds.stability.diff * 0.20) {
      cons.push(t("opt.con.peakRisk"));
    }
  } else {
    if (bounds.endingBalance && s.worstCaseEndingBalance <= bounds.endingBalance.min + bounds.endingBalance.diff * 0.15) {
      pros.push(t("opt.pro.endingBalanceLow"));
    } else if (bounds.endingBalance && s.worstCaseEndingBalance >= bounds.endingBalance.max - bounds.endingBalance.diff * 0.20) {
      cons.push(t("opt.con.endingBalanceHigh"));
    }
  }

  // Refix concentration
  if (bounds.refix && s.expectedMaxConcurrentRefixPercentage <= bounds.refix.min + bounds.refix.diff * 0.15) {
    pros.push(t("opt.pro.refix.spread"));
  } else if (bounds.refix && s.expectedMaxConcurrentRefixPercentage >= bounds.refix.max - bounds.refix.diff * 0.20) {
    cons.push(t("opt.con.refix.concurrent"));
  }

  // Diversification preset: when the user opted into richer candidate sets,
  // refix-spread is the headline benefit. Surface it explicitly even when it
  // is only "above average" rather than top-of-the-front.
  if (diversification && bounds.refix &&
      s.expectedMaxConcurrentRefixPercentage <= bounds.refix.min + bounds.refix.diff * 0.50) {
    if (!pros.some((p) => p === t("opt.pro.refix.spread"))) {
      pros.push(t("opt.pro.div.refixSpread"));
    }
    cons.push(t("opt.con.div.multiTranche"));
  }

  // Term-mode only: affordability breaches + principal paydown
  if (mode === "term") {
    if (bounds.budget && s.expectedAffordabilityBreaches <= bounds.budget.min + bounds.budget.diff * 0.15) {
      pros.push(t("opt.pro.budgetLow"));
    } else if (bounds.budget && s.expectedAffordabilityBreaches >= bounds.budget.max - bounds.budget.diff * 0.20) {
      cons.push(t("opt.con.term.breachHigh"));
    }
    if (bounds.principal && s.expectedEndingBalance <= bounds.principal.min + bounds.principal.diff * 0.15) {
      pros.push(t("opt.pro.term.principalFast"));
    } else if (bounds.principal && s.expectedEndingBalance >= bounds.principal.max - bounds.principal.diff * 0.20) {
      cons.push(t("opt.con.term.principalSlow"));
    }
  } else {
    // Payment-mode: payoff time
    if (bounds.payoff && s.payoffTime <= bounds.payoff.min + bounds.payoff.diff * 0.15) {
      pros.push(t("opt.pro.paymentPayoffClean"));
    } else if (bounds.payoff && s.payoffTime >= bounds.payoff.max - bounds.payoff.diff * 0.20) {
      cons.push(t("opt.con.paymentPayoffUnfinished"));
    }
  }

  // Payment smoothness (term + payment modes; same axis, same copy)
  // Captures month-to-month stability of the scheduled payment stream, distinct
  // from worstCasePayment (single peak) which is covered above.
  if (bounds.smoothness && s.expectedPaymentVolatility <= bounds.smoothness.min + bounds.smoothness.diff * 0.15) {
    pros.push(t("opt.pro.volatilityLow"));
  } else if (bounds.smoothness && s.expectedPaymentVolatility >= bounds.smoothness.max - bounds.smoothness.diff * 0.20) {
    cons.push(t("opt.con.volatilityHigh"));
  }

  // Flexibility
  if (bounds.flex && s.expectedFloatingExposure >= bounds.flex.max - bounds.flex.diff * 0.15) {
    pros.push(t("opt.pro.flex.high"));
  } else if (bounds.flex && s.expectedFloatingExposure <= bounds.flex.min + bounds.flex.diff * 0.20) {
    cons.push(t("opt.con.flex.locked"));
  }

  // Diversification preset: when the user opted into richer candidate sets
  // and the strategy preserves meaningful floating exposure, surface the
  // flexibility benefit explicitly.
  if (diversification && bounds.flex &&
      s.expectedFloatingExposure >= bounds.flex.max - bounds.flex.diff * 0.50 &&
      !pros.some((p) => p === t("opt.pro.flex.high"))) {
    pros.push(t("opt.pro.div.flexPreserve"));
  }

  if (pros.length === 0) {
    pros.push(t("opt.pro.balanced"));
  }
  if (cons.length === 0) {
    cons.push(t("opt.con.noTailDefense"));
  }

  return { pros, cons };
}

/**
 * Optimises and ranks split strategies based on simulation results and user
 * preferences. The objective set and tolerances are selected by `mode` (spec 9.1
 * vs 9.2). Infeasible strategies (any scenario flagged isInfeasible) are dropped
 * from the Pareto set.
 *
 * Returned recommendations carry four sources with distinct semantics (v9):
 *
 *   - `preference`        — the strategy with the lowest overall score under
 *                           the supplied `weights` (or the slider-derived
 *                           defaults when `weights` is omitted). The personalised
 *                           pick that responds to the user's preference
 *                           sliders.
 *
 *   - `lowestCost`        — always the strategy with the smallest
 *                           `expectedInterest`, independent of `weights`.
 *                           The mathematical expected-cost optimum; an
 *                           objective benchmark for comparison. `weights` do
 *                           not influence this slot.
 *
 *   - `mostStable`        — term mode  -> smallest `worstCasePayment`
 *                           (worst-scenario peak across all scenarios);
 *                           payment mode -> smallest `worstCaseEndingBalance`.
 *                           `weights`-independent by design; bound to
 *                           `worstCasePayment` in term mode so the
 *                           recommendation aligns with the `resilience` weight's
 *                           intent of suppressing worst-case peaks.
 *
 *   - `worstCaseDefense`  — the strategy with the smallest
 *                           `worstCaseCompositeScore` (worstCaseInterest 0.5
 *                           + worstCaseAffordabilityBreaches 0.3 +
 *                           worstCasePayment 0.2). `weights`-independent by
 *                           design — the card surfaces the *objective optimum*
 *                           along the same composite axis that the
 *                           `worstCaseDefense` weight modulates in the
 *                           weighted `preference` score. So the user sees both
 *                           the weighted view and the optimum on the same
 *                           composite.
 *
 * The `weights` parameter only changes which strategy lands in `preference`;
 * `lowestCost`, `mostStable`, and `worstCaseDefense` are deliberately
 * weights-agnostic objective baselines. This is product behaviour, not a bug.
 *
 * @param {Object} input
 * @param {any[]} input.simulationResults - All strategy x scenario simulation results
 * @param {any[]} input.scenarios - List of scenarios with probabilities
 * @param {number} [input.sliderCostStability=0.5] - 0 = cost-priority, 1 = stability-priority
 * @param {number} [input.sliderFlexibility=0.0] - 0 = no flex, 1 = high flex
 * @param {{cost?: number, principal?: number, refix?: number, resilience?: number, flex?: number, budget?: number, smoothness?: number, worstCaseDefense?: number}} [input.weights]
 *   - Optional explicit weights. Honoured keys: `cost`, `principal`, `refix`,
 *     `resilience`, `flex`, `budget`, `smoothness` (the 7 preference sliders),
 *     plus `worstCaseDefense` (the 8th v9 key, drives a composite of
 *     worstCaseInterest + worstCaseAffordabilityBreaches + worstCasePayment).
 *     Missing keys default to 0. Sum of present keys must be > 0 or all weights
 *     are ignored. `stability`, `endingBalance`, and `payoff` are NOT read from
 *     this object — in payment mode those keys are derived from
 *     `sliderCostStability` / `sliderFlexibility` via the slider-derived branch
 *     below. These weights only steer the `preference` recommendation;
 *     `lowestCost`, `mostStable`, and `worstCaseDefense` remain
 *     weights-agnostic (see function description).
 * @param {"term"|"payment"} [input.mode] - Mode selector for the objective set (defaults to "term")
 * @param {Record<string, number>} [input.tolerances] - Per-objective tolerance override
 * @param {number} [input.recommendationMinAllocationCount] - Minimum number of
 *   allocations required for the four headline recommendations (v9 forces this
 *   filter on ALL four cards, not just `preference` — see plan v9 H). This
 *   does not filter `rankedStrategies`, so single-product benchmarks can still
 *   appear in the detailed table.
 * @param {boolean} [input.diversification=false] - When true, the user has
 *   opted into the Diversification preset (richer candidate sets + refix-heavy
 *   weights). Pros/cons emission adapts accordingly; ranking and Pareto
 *   classification are unaffected.
 * @param {any[]} [input.strategies] - Optional list of candidate strategies
 *   (same shape produced by the strategy-generator: `{ id, allocations: [{productCode, percentage, ...}] }`).
 *   When provided, used to derive the `concentration` Pareto axis (max single
 *   `allocation.percentage`). When omitted, `concentration` defaults to 1.0
 *   per strategy — backward compatible with callers that don't carry the
 *   generator output. v10 addition.
 * @param {(key: string) => string} [input.t] - Translator for the pros/cons
 *   strings emitted by `generateExplanations`. Defaults to the engine's
 *   built-in Chinese identity translator (`DEFAULT_ZH`), so legacy callers
 *   keep their existing Chinese output verbatim. Pass a translator bound to
 *   the active locale's dictionary to receive English (or any other)
 *   pros/cons. The translator is passed through to `generateExplanations`
 *   unchanged; the engine itself stays i18n-library-free.
 * @returns {any} Ranks, recommendations, and Pareto frontier details
 */
export function optimizeStrategies({
  simulationResults,
  scenarios,
  sliderCostStability = 0.5,
  sliderFlexibility = 0.0,
  weights = undefined,
  mode = "term",
  tolerances = undefined,
  recommendationMinAllocationCount = 1,
  diversification = false,
  strategies = undefined,
  t = identityT
}) {
  // 1. Group simulation results by strategyId
  /** @type {Record<string, any[]>} */
  const strategyGroups = {};
  simulationResults.forEach((/** @type {any} */ res) => {
    if (!strategyGroups[res.strategyId]) {
      strategyGroups[res.strategyId] = [];
    }
    strategyGroups[res.strategyId].push(res);
  });

  const scenarioMap = new Map(scenarios.map(s => [s.id, s]));

  // 2. Aggregate metrics. Strategies with any infeasible scenario are dropped.
  /** @type {any[]} */
  const aggregatedStrategies = [];
  for (const strategyId of Object.keys(strategyGroups)) {
    const runs = strategyGroups[strategyId];
    if (runs.some((/** @type {any} */ r) => r.isInfeasible)) {
      continue;
    }
    const allocationCount = runs[0]?.allocationCount || 1;
    let expectedInterest = 0;
    let expectedRepayments = 0;
    let expectedEndingBalance = 0;
    let expectedMaxPayment = 0;
    let expectedPaymentVolatility = 0;
    let expectedRefixEventCount = 0;
    let expectedMaxConcurrentRefixPercentage = 0;
    let expectedFloatingExposure = 0;
    let expectedAffordabilityBreaches = 0;
    let expectedPayoffTime = 0;

    let worstCasePayment = 0;
    let worstCaseInterest = 0;
    let worstCaseEndingBalance = 0;
    let worstCaseAffordabilityBreaches = 0;
    let bestCaseInterest = Infinity;
    let baseCaseInterest = 0;

    runs.forEach((/** @type {any} */ run) => {
      const scenario = scenarioMap.get(run.scenarioId);
      const prob = scenario ? scenario.probability : 0;

      expectedInterest += run.totalInterest * prob;
      expectedRepayments += run.totalRepayments * prob;
      expectedEndingBalance += run.endingBalance * prob;
      expectedMaxPayment += run.maximumPayment * prob;
      expectedPaymentVolatility += run.paymentVolatility * prob;
      expectedRefixEventCount += run.refixEventCount * prob;
      expectedMaxConcurrentRefixPercentage += run.maximumConcurrentRefixPercentage * prob;
      expectedFloatingExposure += run.floatingExposure * prob;
      expectedAffordabilityBreaches += run.affordabilityBreaches * prob;
      expectedPayoffTime += (run.payoffTime || 0) * prob;

      if (run.maximumPayment > worstCasePayment) worstCasePayment = run.maximumPayment;
      if (run.endingBalance > worstCaseEndingBalance) worstCaseEndingBalance = run.endingBalance;
      if (run.totalInterest < bestCaseInterest) bestCaseInterest = run.totalInterest;
      if (run.totalInterest > worstCaseInterest) worstCaseInterest = run.totalInterest;
      if (run.affordabilityBreaches > worstCaseAffordabilityBreaches) worstCaseAffordabilityBreaches = run.affordabilityBreaches;
      if (run.scenarioId === "base") {
        baseCaseInterest = run.totalInterest;
      }
    });

    expectedInterest = Math.round(expectedInterest * 100) / 100;
    expectedRepayments = Math.round(expectedRepayments * 100) / 100;
    expectedEndingBalance = Math.round(expectedEndingBalance * 100) / 100;
    expectedMaxPayment = Math.round(expectedMaxPayment * 100) / 100;
    expectedPaymentVolatility = Math.round(expectedPaymentVolatility * 100) / 100;
    expectedRefixEventCount = Math.round(expectedRefixEventCount * 100) / 100;
    expectedMaxConcurrentRefixPercentage = Math.round(expectedMaxConcurrentRefixPercentage * 1e4) / 1e4;
    expectedFloatingExposure = Math.round(expectedFloatingExposure * 1e4) / 1e4;
    expectedAffordabilityBreaches = Math.round(expectedAffordabilityBreaches * 10) / 10;
    expectedPayoffTime = Math.round(expectedPayoffTime);
    worstCaseInterest = Math.round(worstCaseInterest * 100) / 100;
    worstCaseEndingBalance = Math.round(worstCaseEndingBalance * 100) / 100;

    // v10: derive `concentration` from the strategy-generator output's
    // allocations. When the caller does not pass `strategies`, fall back
    // to 1.0 (single-allocation) so legacy callers stay unaffected.
    const stratEntry = strategies && Array.isArray(strategies)
      ? strategies.find((/** @type {any} */ x) => x.id === strategyId || x.strategyId === strategyId)
      : undefined;
    const concentration = stratEntry && Array.isArray(stratEntry.allocations) && stratEntry.allocations.length > 0
      ? Math.max(...stratEntry.allocations.map((/** @type {any} */ a) => Number(a.percentage) || 0))
      : 1.0;

    aggregatedStrategies.push({
      strategyId,
      allocationCount,
      expectedInterest,
      expectedRepayments,
      expectedEndingBalance,
      expectedMaxPayment,
      expectedPaymentVolatility,
      expectedRefixEventCount,
      expectedMaxConcurrentRefixPercentage,
      expectedFloatingExposure,
      expectedAffordabilityBreaches,
      expectedPayoffTime,
      worstCasePayment,
      worstCaseInterest,
      worstCaseEndingBalance,
      worstCaseAffordabilityBreaches,
      bestCaseInterest,
      baseCaseInterest,
      // Derived Pareto key (spec 9.1: 1 - expectedFloatingExposure).
      flexibilityPenalty: Math.round((1 - expectedFloatingExposure) * 1e4) / 1e4,
      // v10: max single allocation share, surfaced as a Pareto axis so a
      // single-product 100% strategy is dominated by any split.
      concentration: Math.round(concentration * 1e4) / 1e4
    });
  }

  if (aggregatedStrategies.length === 0) {
    return { rankedStrategies: [], recommendations: {} };
  }

  // 3. Pareto frontier classification (tolerance-aware, per spec 9.3).
  const { objectives, tolerances: tolSet } = mode === "payment"
    ? getPaymentObjectives(tolerances)
    : getTermObjectives(tolerances);

  /** @type {Record<string, boolean>} */
  const paretoStatus = {};
  aggregatedStrategies.forEach((/** @type {any} */ s) => {
    const dominated = aggregatedStrategies.some((/** @type {any} */ other) => other !== s && dominates(other, s, objectives, tolSet));
    paretoStatus[s.strategyId] = !dominated;
  });

  // 4. Normalisation bounds
  const bounds = {
    cost: getBoundsFor(aggregatedStrategies, "expectedInterest"),
    principal: getBoundsFor(aggregatedStrategies, "expectedEndingBalance"),
    refix: getBoundsFor(aggregatedStrategies, "expectedMaxConcurrentRefixPercentage"),
    resilience: getBoundsFor(aggregatedStrategies, "worstCasePayment"),
    flex: getBoundsFor(aggregatedStrategies, "expectedFloatingExposure"),
    stability: getBoundsFor(aggregatedStrategies, "expectedMaxPayment"),
    budget: getBoundsFor(aggregatedStrategies, "expectedAffordabilityBreaches"),
    endingBalance: getBoundsFor(aggregatedStrategies, "worstCaseEndingBalance"),
    payoff: getBoundsFor(aggregatedStrategies, "expectedPayoffTime"),
    smoothness: getBoundsFor(aggregatedStrategies, "expectedPaymentVolatility"),
    // v9: 3 new Pareto-objective normalisation bounds. Each call is a no-op
    // when all strategies share the same value (diff falls back to 1 — see
    // getBoundsFor); the composite score below relies on that fallback so it
    // remains defined even on a single-strategy candidate set.
    worstCaseInterest: getBoundsFor(aggregatedStrategies, "worstCaseInterest"),
    worstCaseBreaches: getBoundsFor(aggregatedStrategies, "worstCaseAffordabilityBreaches"),
    refixEventCount: getBoundsFor(aggregatedStrategies, "expectedRefixEventCount"),
    // v10: concentration normalisation bound for the per-axis score below.
    concentration: getBoundsFor(aggregatedStrategies, "concentration")
  };

  // 5. Weight calculation (mode-aware per spec 10.2)
  let wCost, wPrincipal, wRefix, wResilience, wFlex, wStability, wBudget, wEndingBalance, wPayoff, wSmoothness, wWorstCaseDefense;
  if (weights) {
    const totalRaw = (weights.cost || 0) +
      (weights.principal || 0) +
      (weights.refix || 0) +
      (weights.resilience || 0) +
      (weights.flex || 0) +
      (weights.budget || 0) +
      (weights.smoothness || 0) +
      (weights.worstCaseDefense || 0) || 1;
    wCost = (weights.cost || 0) / totalRaw;
    wPrincipal = (weights.principal || 0) / totalRaw;
    wRefix = (weights.refix || 0) / totalRaw;
    wResilience = (weights.resilience || 0) / totalRaw;
    wFlex = (weights.flex || 0) / totalRaw;
    wBudget = (weights.budget || 0) / totalRaw;
    wSmoothness = (weights.smoothness || 0) / totalRaw;
    // v9: 8th weight key. Drives a composite of worstCaseInterest +
    // worstCaseAffordabilityBreaches + worstCasePayment (see
    // worstCaseCompositeScore). 0 by default for backward-compat with
    // legacy callers that don't set it.
    wWorstCaseDefense = (weights.worstCaseDefense || 0) / totalRaw;
    wStability = 0;
    wEndingBalance = 0;
    wPayoff = 0;
  } else if (mode === "payment") {
    const rawCostWeight = 0.50 - sliderCostStability * 0.30;
    const rawEndingBalance = 0.20 + sliderCostStability * 0.20;
    const rawPayoffWeight = 0.10;
    const rawRefixWeight = 0.10;
    const rawFlexibilityWeight = sliderFlexibility * 0.20;
    const totalRaw = rawCostWeight + rawEndingBalance + rawPayoffWeight + rawRefixWeight + rawFlexibilityWeight;
    wCost = rawCostWeight / totalRaw;
    wEndingBalance = rawEndingBalance / totalRaw;
    wPayoff = rawPayoffWeight / totalRaw;
    wRefix = rawRefixWeight / totalRaw;
    wFlex = rawFlexibilityWeight / totalRaw;
    wPrincipal = 0;
    wStability = 0;
    wResilience = 0;
    wBudget = 0;
    wSmoothness = 0;
    wWorstCaseDefense = 0;
  } else {
    const rawCostWeight = 0.65 - sliderCostStability * 0.40;
    const rawStabilityWeight = 0.15 + sliderCostStability * 0.30;
    const rawRefixWeight = 0.15 + sliderCostStability * 0.10;
    const rawResilienceWeight = 0.05 + sliderCostStability * 0.05;
    const rawFlexibilityWeight = sliderFlexibility * 0.20;
    const totalRaw = rawCostWeight + rawStabilityWeight + rawRefixWeight + rawResilienceWeight + rawFlexibilityWeight;
    wCost = rawCostWeight / totalRaw;
    wStability = rawStabilityWeight / totalRaw;
    wRefix = rawRefixWeight / totalRaw;
    wResilience = rawResilienceWeight / totalRaw;
    wFlex = rawFlexibilityWeight / totalRaw;
    wPrincipal = 0;
    wBudget = 0;
    wEndingBalance = 0;
    wPayoff = 0;
    wSmoothness = 0;
    wWorstCaseDefense = 0;
  }

  // 6. Score and rank strategies
  // v9: composite worst-case score. Combines the three worst-case axes
  // (interest / breaches / payment) with a 0.5 / 0.3 / 0.2 weighting so the
  // single `worstCaseDefense` slider can express the user's "I am most
  // worried about the bad tail" preference without per-axis tuning. Falls
  // back to a 0 contribution when all strategies tie on an axis (diff=1
  // after getBoundsFor fallback).
  /**
   * @param {any} s
   * @param {Record<string, {min: number, max: number, diff: number}>} bounds
   * @returns {number}
   */
  const worstCaseCompositeScore = (s, bounds) => {
    const wci = (s.worstCaseInterest - bounds.worstCaseInterest.min) / (bounds.worstCaseInterest.diff || 1);
    const wcb = (s.worstCaseAffordabilityBreaches - bounds.worstCaseBreaches.min) / (bounds.worstCaseBreaches.diff || 1);
    const wcp = (s.worstCasePayment - bounds.resilience.min) / (bounds.resilience.diff || 1);
    return wci * 0.5 + wcb * 0.3 + wcp * 0.2;
  };

  const scoredStrategies = aggregatedStrategies.map((/** @type {any} */ s) => {
    const costScore = (s.expectedInterest - bounds.cost.min) / bounds.cost.diff;
    const principalScore = (s.expectedEndingBalance - bounds.principal.min) / bounds.principal.diff;
    const refixScore = (s.expectedMaxConcurrentRefixPercentage - bounds.refix.min) / bounds.refix.diff;
    const resilienceScore = (s.worstCasePayment - bounds.resilience.min) / bounds.resilience.diff;
    const flexibilityScore = (bounds.flex.max - s.expectedFloatingExposure) / bounds.flex.diff;
    const stabilityScore = (s.expectedMaxPayment - bounds.stability.min) / bounds.stability.diff;
    const budgetScore = (s.expectedAffordabilityBreaches - bounds.budget.min) / bounds.budget.diff;
    const endingBalanceScore = (s.worstCaseEndingBalance - bounds.endingBalance.min) / bounds.endingBalance.diff;
    const payoffScore = (s.expectedPayoffTime - bounds.payoff.min) / bounds.payoff.diff;
    const smoothnessScore = (s.expectedPaymentVolatility - bounds.smoothness.min) / bounds.smoothness.diff;
    // v9: 3 new normalised Pareto scores for the worst-case axes. These
    // participate in the dominance check (via the objectives list) but NOT
    // in the weighted-sum — only the composite `worstCaseDefense` does,
    // through wWorstCaseDefense * worstCaseCompositeScore below.
    const worstCaseInterestScore = (s.worstCaseInterest - bounds.worstCaseInterest.min) / (bounds.worstCaseInterest.diff || 1);
    const worstCaseBreachesScore = (s.worstCaseAffordabilityBreaches - bounds.worstCaseBreaches.min) / (bounds.worstCaseBreaches.diff || 1);
    const refixEventCountScore = (s.expectedRefixEventCount - bounds.refixEventCount.min) / (bounds.refixEventCount.diff || 1);
    // v10: per-axis normalised concentration score. Like the v9 worst-case
    // axes, this is Pareto-only — it does NOT feed `overallScore` (no
    // `wConcentration` slider). Surfaced on each ranked strategy so the
    // Pareto table column can show the normalised position.
    const concentrationScore = (s.concentration - bounds.concentration.min) / (bounds.concentration.diff || 1);

    const overallScore = wCost * costScore +
      wPrincipal * principalScore +
      wRefix * refixScore +
      wResilience * resilienceScore +
      wFlex * flexibilityScore +
      wStability * stabilityScore +
      wBudget * budgetScore +
      wEndingBalance * endingBalanceScore +
      wPayoff * payoffScore +
      wSmoothness * smoothnessScore +
      // v9: composite worst-case score. Driven by the 8th weight key
      // `worstCaseDefense` (which defaults to 0 for legacy callers).
      wWorstCaseDefense * worstCaseCompositeScore(s, bounds);

    return {
      ...s,
      isParetoOptimal: paretoStatus[s.strategyId],
      score: Math.round(overallScore * 1000) / 1000,
      // v9: surface the per-axis scores for the UI's worst-case defense card
      // and the strategy-detail modal's "trade-off" breakdown. Rounded to
      // 3dp like the overall score.
      worstCaseInterestScore: Math.round(worstCaseInterestScore * 1000) / 1000,
      worstCaseBreachesScore: Math.round(worstCaseBreachesScore * 1000) / 1000,
      refixEventCountScore: Math.round(refixEventCountScore * 1000) / 1000,
      worstCaseCompositeScore: Math.round(worstCaseCompositeScore(s, bounds) * 1000) / 1000,
      // v10: Pareto-only — surfaced for the Pareto table column / detail modal.
      concentrationScore: Math.round(concentrationScore * 1000) / 1000
    };
  });

  scoredStrategies.sort((a, b) => a.score - b.score);

  // 7. Recommendations: 4 slots (v9) — preference + lowestCost + mostStable +
  // worstCaseDefense. The previous release exposed 10 objective benchmarks;
  // v9 collapses them into 4 cards (see plan v9 "G. PickMin → 4 recommendation
  // slots"). The remaining 6 axes are still observable in the Pareto table
  // and StrategyDetailModal.
  //
  //   - `preference`        : weighted-sum preference (responds to `weights`).
  //   - `lowestCost`        : smallest `expectedInterest` (term & payment).
  //                            Weights-independent by design.
  //   - `mostStable`        : term -> smallest `worstCasePayment`,
  //                            payment -> smallest `worstCaseEndingBalance`.
  //                            Weights-independent by design.
  //   - `worstCaseDefense`  : smallest `worstCaseCompositeScore` — the same
  //                            composite used in the overallScore formula
  //                            (worstCaseInterest 0.5 + worstCaseAffordability
  //                            Breaches 0.3 + worstCasePayment 0.2). Responds
  //                            to the 8th weight key, but the card itself is
  //                            the *objective optimum* along that composite,
  //                            so the user sees both the weighted view
  //                            (preference) and the optimum (worstCaseDefense).
  //
  // v10 mutex: each card is forced to pick a DIFFERENT strategy when 2+
  // candidates exist. Picker ordering is fixed:
  //     preference -> lowestCost -> mostStable -> worstCaseDefense
  // Each pick excludes all previously-picked strategyIds from the candidate
  // pool. If the filtered pool is empty (only 1 viable candidate), the picker
  // falls back to the full pool so the 4 cards all return that single
  // strategy. This guarantees that with 3+ distinct candidates, the 4 cards
  // surface 4 different strategies — preventing the v9 bug where the 3
  // benchmark cards could all lock onto the same "lowestCost" pick.
  //
  // All four slots share the same `recommendationCandidates` pool — v9 forces
  // every card to prefer ≥2-allocation strategies when the constraint is
  // active, so the single-product extreme (e.g. "100% floating") never wins
  // any of the 4 cards unless no split exists.
  const recommendationPool = scoredStrategies.filter(
    (/** @type {any} */ s) => (s.allocationCount || 1) >= recommendationMinAllocationCount
  );
  const recommendationCandidates = recommendationPool.length > 0 ? recommendationPool : scoredStrategies;
  const preference = recommendationCandidates[0];

  /**
   * Small-pool fallback contract: when the pool is small (≤2 strategies) the
   * picker falls back to the global minimum over the unfiltered pool. This can
   * re-pick an already-excluded strategy, but guarantees the 4 cards always
   * render a non-undefined pick. Documented for the v10 review.
   * @param {any[]} pool
   * @param {string} key
   * @param {(a: any, b: any) => number} [cmp]
   * @returns {any}
   */
  const pickMin = (pool, key, cmp) => [...pool].sort((a, b) =>
    cmp ? cmp(a[key], b[key]) : (a[key] ?? Infinity) - (b[key] ?? Infinity)
  )[0];

  // v10: mutex-aware pickers. `excludedStrategyIds` accumulates the picks
  // from earlier cards; each subsequent pick filters the pool. If filtering
  // empties the pool, the picker falls back to the full pool (small-pool
  // fallback) so a single viable candidate is returned by every card
  // instead of `undefined`.
  /** @type {Set<string>} */
  const excludedStrategyIds = new Set();
  /**
   * Mutex-aware picker. Filters out `excludedStrategyIds`; if the filtered pool
   * is empty, falls back to `pickMin(pool, ...)` over the unfiltered pool (see
   * the small-pool fallback contract on `pickMin`). This is the small-pool
   * invariant: the 4 cards always render a non-undefined pick, even if it
   * duplicates an earlier card's pick.
   * @param {any[]} pool
   * @param {string} key
   * @param {(a: any, b: any) => number} [cmp]
   * @returns {any}
   */
  const pickExcluding = (pool, key, cmp) => {
    const filtered = pool.filter((/** @type {any} */ s) => !excludedStrategyIds.has(s.strategyId));
    if (filtered.length === 0) return pickMin(pool, key, cmp); // small-pool fallback
    return pickMin(filtered, key, cmp);
  };
  /**
   * Composite-score picker that mirrors `pickExcluding` semantics but sorts
   * by the precomputed `worstCaseCompositeScore` instead of a single key.
   * @param {any[]} pool
   * @returns {any}
   */
  const pickExcludingComposite = (pool) => {
    const filtered = pool.filter((/** @type {any} */ s) => !excludedStrategyIds.has(s.strategyId));
    if (filtered.length === 0) {
      return [...pool].sort((a, b) => (a.worstCaseCompositeScore ?? 0) - (b.worstCaseCompositeScore ?? 0))[0];
    }
    return [...filtered].sort((a, b) => (a.worstCaseCompositeScore ?? 0) - (b.worstCaseCompositeScore ?? 0))[0];
  };

  excludedStrategyIds.add(preference.strategyId);
  const lowestCost = pickExcluding(recommendationCandidates, "expectedInterest");
  excludedStrategyIds.add(lowestCost.strategyId);
  const mostStable = mode === "payment"
    ? pickExcluding(recommendationCandidates, "worstCaseEndingBalance")
    : pickExcluding(recommendationCandidates, "worstCasePayment");
  excludedStrategyIds.add(mostStable.strategyId);
  const worstCaseDefense = pickExcludingComposite(recommendationCandidates);

  const buildRecObject = (/** @type {any} */ s) => {
    if (!s) return null;
    const { pros, cons } = generateExplanations(s, bounds, mode, { diversification, t });
    return {
      strategyId: s.strategyId,
      score: s.score,
      isParetoOptimal: s.isParetoOptimal,
      pros,
      cons
    };
  };

  return {
    rankedStrategies: scoredStrategies,
    recommendations: {
      preference: buildRecObject(preference),
      lowestCost: buildRecObject(lowestCost),
      mostStable: buildRecObject(mostStable),
      worstCaseDefense: buildRecObject(worstCaseDefense)
    }
  };
}
